### ISSUE TITLE
Deploy Farcaster Hats Delegator contracts via herocast

### ISSUE THREAD

**Issue by hellno** [hellno/herocast#123]
- move all Hats Protocol related components onto a separate page
- requires an existing Hats Protocol tree (=permissions setup) plus admin hats and caster hat

- optional: one click deploy a "pre-filled Hats tree" that requires as little input from user as possible

**Comment by spengrah** [comment]
> requires an existing Hats Protocol tree (=permissions setup) plus admin hats and caster hat

Tree needs at minimum 2 hats
1. ownerHat
2. casterHat

The ownerHat in most cases should/will be an admin (parent) of the casterHat, but this is not strictly necessary. The top hat of the tree can serve as the ownerHat, but doesn't need to.

**Comment by hellno** [comment]
closed by #143
