### ISSUE TITLE
Register new Farcaster accounts via herocast

### ISSUE THREAD

**Issue by hellno** [hellno/herocast#124]
- add UX to register new Farcaster accounts, instead of only allowing existing Farcaster accounts to get connected
- allow setting a name and profile
- make sure UI isn't ultra confusing

**Comment by spengrah** [comment]
Another other fid/profile settings is connected addresses, but probably out of scope here

**Comment by spengrah** [comment]
Setting a profile pic/image is also important

**Comment by hellno** [comment]
closed by #143
