### ISSUE TITLE
Users I don't follow in the following feed?

### ISSUE THREAD

**Issue by scottrepreneur** [hellno/herocast#233]
Not sure if there's an algo pulling these in, but not quite accurate if supposed to be only people I'm following.

<img width="624" alt="Screenshot 2024-04-25 at 08 43 23" src="https://github.com/hellno/herocast/assets/1778380/a3ed4cc3-60ca-41a3-a5be-597b7e8c43b9">

**Comment by hellno** [comment]
oh good point! I think those are recasts. Checking with Neynar API how this is represented in the data and will signal it in the feed

**Comment by hellno** [comment]
<img width="414" alt="image" src="https://github.com/hellno/herocast/assets/686075/867b22c6-89ae-493a-aa02-b7d8b52c19cf">
added a recast indicator, see image. worked with neynar as they offer a different feed endpoint to fetch a following feed that has this data 🙏
